# Utilización del paquete sklearn para calcular la medida mAP
1. Dada una imagen query perteneciente al conjunto probe, generar un vector con la misma dimensión que el tamaño de la galería con las posiciones que coinciden con la identidad de la imagen query a 1 y el resto a 0.
2. Calcular las distancias de la imagen query a todas las de la librería.
3. A partir de las distancias anteriores obtener un vector de similitud con la imagen de query como 1 - distancia / max(distancia)
4. Utilizar la función average_precision_score con el vector *y_true* como el calculado en el punto 1 e *y_score* el vector calculado en el punto 3, para calcular la AP de la imagen query
5. Repetir los pasos del 1 al 4 para todas las imágenes del conjunto de probe y obtener el valor promedio de AP para calcular el mAP

In [ ]:
import numpy as np
from sklearn.metrics import average_precision_score, precision_recall_curve, auc

## Ejemplo 1
Las posiciones 1, 4 y 5 de la galería coinciden con la identidad de la imagen query por tanto estas posiciones están como 1 y el resto como 0

Este ejemplo coincide con el segundo caso de los representados en

https://towardsdatascience.com/breaking-down-mean-average-precision-map-ae462f623a52


In [ ]:
coincidencias_galeria = np.array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0])

El vector de distancias de la imagen de probe con la clase es el siguiente

In [ ]:
dist_query_galeria = np.array([2, 12, 23, 5, 6, 8, 9, 11, 29, 17])

In [ ]:
similitud_query_galeria = 1 - dist_query_galeria / np.amax(dist_query_galeria)
print('Vector similitudes: {}'.format(similitud_query_galeria))

Vector similitudes: [0.93103448 0.5862069  0.20689655 0.82758621 0.79310345 0.72413793
 0.68965517 0.62068966 0.         0.4137931 ]


In [ ]:
indices = np.argsort(1 - similitud_query_galeria)
print(indices)
print(coincidencias_galeria[indices])

[0 3 4 5 6 7 1 9 2 8]
[1 1 1 0 0 0 0 0 0 0]


In [ ]:
ap = average_precision_score(coincidencias_galeria, similitud_query_galeria, average='macro', pos_label=1)
print('Average precision (AP): {:.2f}'.format(ap))

Average precision (AP): 1.00


## Ejemplo 2
Las posiciones 1, 4 y 5 de la galería coinciden con la identidad de la imagen query por tanto estas posiciones están como 1 y el resto como 

Este ejemplo coincide con el primer caso de los representados en

https://towardsdatascience.com/breaking-down-mean-average-precision-map-ae462f623a52


El vector de distancias de la imagen de probe con la clase es el siguiente

In [ ]:
dist_query_galeria = np.array([1, 15, 19, 8, 9, 12, 23, 3, 14, 5])

In [ ]:
similitud_query_galeria = 1 - dist_query_galeria / np.amax(dist_query_galeria)
print('Vector similitudes: {}'.format(similitud_query_galeria))

Vector similitudes: [0.95652174 0.34782609 0.17391304 0.65217391 0.60869565 0.47826087
 0.         0.86956522 0.39130435 0.7826087 ]


In [ ]:
print(1 - similitud_query_galeria)
indices = np.argsort(1 - similitud_query_galeria)
print(indices)
print(coincidencias_galeria[indices])

[0.04347826 0.65217391 0.82608696 0.34782609 0.39130435 0.52173913
 1.         0.13043478 0.60869565 0.2173913 ]
[0 7 9 3 4 5 8 1 2 6]
[1 0 0 1 1 0 0 0 0 0]


In [ ]:
ap = average_precision_score(coincidencias_galeria, similitud_query_galeria, average='macro', pos_label=1)
print('Average precision (AP): {:.2f}'.format(ap))

Average precision (AP): 0.70


In [ ]:
prob_query_galeria = np.array([0.9, 0.0, 0, 0.4, 0.5, 0, 0, 0.8, 0, 0.8])
tmp = 1 - prob_query_galeria
print(tmp)

[0.1 1.  1.  0.6 0.5 1.  1.  0.2 1.  0.2]


In [ ]:
ap = average_precision_score(coincidencias_galeria, prob_query_galeria, average='macro', pos_label=1)
print(ap)

0.7


In [ ]:
indices = np.argsort(tmp)
print(tmp)
print(indices)

[0.1 1.  1.  0.6 0.5 1.  1.  0.2 1.  0.2]
[0 7 9 4 3 1 2 5 6 8]


In [ ]:
print(coincidencias_galeria[indices])

[1 0 0 1 1 0 0 0 0 0]
